// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxdqRe-F1kwuYV-xPwz5ThGL_l14Yd20I',
    appId: '1:648080058477:web:bde744918a753cd2a2f764',
    messagingSenderId: '648080058477',
    projectId: 'flutter-e-commerce-9ab54',
    authDomain: 'flutter-e-commerce-9ab54.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-9ab54.appspot.com',
    measurementId: 'G-BMLB45TMM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzs2rXrD5_0UplmiYFasi7LnLEeZj_UM',
    appId: '1:648080058477:android:5fafa695db907554a2f764',
    messagingSenderId: '648080058477',
    projectId: 'flutter-e-commerce-9ab54',
    storageBucket: 'flutter-e-commerce-9ab54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2Z-iksLkBjIy1-5FcjlpameoF4hyrvU',
    appId: '1:648080058477:ios:68326b3601025240a2f764',
    messagingSenderId: '648080058477',
    projectId: 'flutter-e-commerce-9ab54',
    storageBucket: 'flutter-e-commerce-9ab54.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2Z-iksLkBjIy1-5FcjlpameoF4hyrvU',
    appId: '1:648080058477:ios:68326b3601025240a2f764',
    messagingSenderId: '648080058477',
    projectId: 'flutter-e-commerce-9ab54',
    storageBucket: 'flutter-e-commerce-9ab54.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxdqRe-F1kwuYV-xPwz5ThGL_l14Yd20I',
    appId: '1:648080058477:web:35b4c7d6445b87cda2f764',
    messagingSenderId: '648080058477',
    projectId: 'flutter-e-commerce-9ab54',
    authDomain: 'flutter-e-commerce-9ab54.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-9ab54.appspot.com',
    measurementId: 'G-BCBZ1LHRMF',
  );
}
